### ISSUE TITLE
Instant preview, cross jump not working for Asahi Linux on apple silicon

### ISSUE THREAD

**Issue by physicophilic** [chomosuke/typst-preview.nvim#56]
After a successful `TypstPreviewUpdate` on my Asahi Linux on M1 macbook, I am able to see preview but there are 2 issues:

1. It is not instant; works on save.
2. Backward jump from preview to file isn't working.

I confirm that on my Intel machine running ubuntu 22 it works out of the box.

Is this a bug, or a limitation?

**Comment by chomosuke** [comment]
Hello, can you head over to [tinymist](https://github.com/Myriad-Dreamin/tinymist) and confirm that the issue doesn't exist for the vs code plugin of tinymist.

If the issue exist for the vscode plugin, please open an issue for tinymist.

If the issue is specific to this repository. Please reopen this issue.

**Comment by physicophilic** [comment]
Yes, it is an issue of tinymist, and I already opened an issue there.
